version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: jointecnologia
    networks:
      - jointecnologia-net

volumes:
  postgres-data:

networks:
  jointecnologia-net:
    driver: bridge
